API_BASE_URL = "https://192.168.130.4/api/v1"

UPDATE_INTERVAL = 5

SERIAL_PORT = "/dev/ttyUSB1"
BAUDRATE = 115200

ERROR_LOG_FILE = "logs/errors.log"
VALIDATION_LOG_FILE = "logs/validation.log"

DATABASE_NAME = "airport_logs.db"

ACTIVE_STATUS = "actief"
INACTIVE_STATUS = "inactief"
MAINTENANCE_STATUS = "onderhoud"
ERROR_STATUS = "error"

BAG_UNDERWAY_STATUS = "onderweg"
BAG_DELIVERED_STATUS = "afgeleverd"
BAG_STORED_STATUS = "opgeslagen"
BAG_LOST_STATUS = "zoek"

TARGET_PROCESSING_TIME = 5

# KPI thresholds

GOOD_HEALTH_SCORE = 85
WARNING_HEALTH_SCORE = 70

GOOD_AVAILABILITY = 90
WARNING_AVAILABILITY = 75

GOOD_ACCURACY = 98
WARNING_ACCURACY = 95

GOOD_COMPLETION = 90
WARNING_COMPLETION = 75

GOOD_DELAY_RATE = 5
WARNING_DELAY_RATE = 15